[Paths]
# 基础数据存放路径 (用户数据、内置探针、条形码、基因组配置等)
data_dir = /home/qzhang/new/U-Probe/data
# 基因组数据存放基目录
genomes_dir = /home/qzhang/genomes
# 任务结果存放路径
results_dir = /home/qzhang/new/U-Probe/data/results
# Fisheye工具路径
fisheye_dir = /home/qzhang/fisheye
