name: uprobe

channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults

dependencies:
  - python=3.9
  - pysam
  - bowtie2
  - blast
  - mmseqs2
  - pip
  - pip:
      - -r requirements.txt
