"""
HTML report generation for U-Probe analysis.
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional
import pandas as pd

from uprobe.utils import get_logger

logger = get_logger(__name__)


def get_basic_template() -> str:
    """Get basic HTML template."""
    return '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>U-Probe Analysis Report - {protocol_name}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            background-color: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .header {{
            text-align: center;
            border-bottom: 2px solid #007acc;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            color: #007acc;
            margin: 0;
            font-size: 2.5em;
        }}
        .header .subtitle {{
            color: #666;
            font-size: 1.2em;
            margin-top: 10px;
        }}
        .section {{
            margin-bottom: 30px;
        }}
        .section h2 {{
            color: #007acc;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
            font-size: 1.8em;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin: 15px 0;
        }}
        .stat-card {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 6px;
            border-left: 3px solid #007acc;
            text-align: center;
        }}
        .stat-value {{
            font-size: 1.5em;
            font-weight: bold;
            color: #007acc;
            margin-bottom: 3px;
        }}
        .stat-label {{
            color: #666;
            font-size: 0.9em;
        }}
        .table-container {{
            overflow-x: auto;
            margin: 20px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background: white;
        }}
        th, td {{
            padding: 8px 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            font-size: 0.9em;
        }}
        th {{
            background-color: #007acc;
            color: white;
            font-weight: bold;
        }}
        tr:nth-child(even) {{
            background-color: #f8f9fa;
        }}
        .plot-container {{
            text-align: center;
            margin: 15px 0;
            padding: 10px;
        }}
        .plot-container img {{
            max-width: 80%;
            max-height: 400px;
            height: auto;
            border-radius: 6px;
            box-shadow: 0 1px 4px rgba(0,0,0,0.1);
        }}
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>U-Probe Analysis Report</h1>
            <div class="subtitle">Protocol: {protocol_name}</div>
            <div class="subtitle">Generated: {timestamp}</div>
        </div>
        
        {content}
        
        <div class="footer">
            <p>Generated by U-Probe Analysis Pipeline</p>
            <p>Report Type: Basic Template</p>
        </div>
    </div>
</body>
</html>
'''


def get_detailed_template() -> str:
    """Get detailed HTML template with enhanced styling."""
    return '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>U-Probe Detailed Analysis Report - {protocol_name}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        }}
        .container {{
            background-color: white;
            padding: 40px;
            border-radius: 15px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }}
        .header {{
            text-align: center;
            border-bottom: 3px solid #007acc;
            padding-bottom: 25px;
            margin-bottom: 40px;
            background: linear-gradient(135deg, #007acc, #0056b3);
            color: white;
            margin: -40px -40px 40px -40px;
            padding: 40px;
            border-radius: 15px 15px 0 0;
        }}
        .header h1 {{
            margin: 0;
            font-size: 3em;
            text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }}
        .header .subtitle {{
            font-size: 1.3em;
            margin-top: 15px;
            opacity: 0.9;
        }}
        .section {{
            margin-bottom: 40px;
        }}
        .section h2 {{
            color: #007acc;
            border-bottom: 2px solid #007acc;
            padding-bottom: 15px;
            font-size: 2em;
            position: relative;
        }}
        .section h2:before {{
            content: '';
            position: absolute;
            bottom: -2px;
            left: 0;
            width: 50px;
            height: 2px;
            background: #28a745;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 18px;
            margin: 18px 0;
        }}
        .stat-card {{
            background: linear-gradient(135deg, #f8f9fa, #e9ecef);
            padding: 18px;
            border-radius: 10px;
            border-left: 4px solid #007acc;
            text-align: center;
            transition: transform 0.3s ease;
        }}
        .stat-card:hover {{
            transform: translateY(-5px);
            box-shadow: 0 8px 25px rgba(0,0,0,0.15);
        }}
        .stat-value {{
            font-size: 1.8em;
            font-weight: bold;
            color: #007acc;
            margin-bottom: 6px;
        }}
        .stat-label {{
            color: #666;
            font-size: 1em;
            font-weight: 500;
        }}
        .table-container {{
            overflow-x: auto;
            margin: 25px 0;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            background: white;
        }}
        th, td {{
            padding: 10px 15px;
            text-align: left;
            border-bottom: 1px solid #e9ecef;
            font-size: 0.9em;
        }}
        th {{
            background: linear-gradient(135deg, #007acc, #0056b3);
            color: white;
            font-weight: bold;
            font-size: 1.1em;
        }}
        tr:nth-child(even) {{
            background-color: #f8f9fa;
        }}
        tr:hover {{
            background-color: #e3f2fd;
        }}
        .plot-container {{
            text-align: center;
            margin: 20px 0;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 10px;
        }}
        .plot-container img {{
            max-width: 75%;
            max-height: 350px;
            height: auto;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.15);
        }}
        .plot-title {{
            font-size: 1.3em;
            font-weight: bold;
            color: #007acc;
            margin-bottom: 15px;
        }}
        .method-info {{
            background: #e8f4f8;
            padding: 20px;
            border-radius: 10px;
            border-left: 5px solid #17a2b8;
            margin: 20px 0;
        }}
        .method-info h3 {{
            color: #17a2b8;
            margin-top: 0;
        }}
        .footer {{
            text-align: center;
            margin-top: 50px;
            padding-top: 25px;
            border-top: 2px solid #e9ecef;
            color: #666;
        }}
        .collapsible {{
            background-color: #f1f1f1;
            color: #444;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            border-radius: 5px;
            margin: 5px 0;
        }}
        .collapsible:hover {{
            background-color: #ddd;
        }}
        .collapsible-content {{
            padding: 0 18px;
            display: none;
            overflow: hidden;
            background-color: #f9f9f9;
            border-radius: 5px;
        }}
    </style>
    <script>
        document.addEventListener('DOMContentLoaded', function() {{
            var coll = document.getElementsByClassName("collapsible");
            for (var i = 0; i < coll.length; i++) {{
                coll[i].addEventListener("click", function() {{
                    this.classList.toggle("active");
                    var content = this.nextElementSibling;
                    if (content.style.display === "block") {{
                        content.style.display = "none";
                    }} else {{
                        content.style.display = "block";
                    }}
                }});
            }}
        }});
    </script>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>U-Probe Detailed Analysis Report</h1>
            <div class="subtitle">Protocol: {protocol_name}</div>
            <div class="subtitle">Generated: {timestamp}</div>
        </div>
        
        {content}
        
        <div class="footer">
            <p><strong>Generated by U-Probe Analysis Pipeline</strong></p>
            <p>Report Type: Detailed Template | Version 1.0</p>
        </div>
    </div>
</body>
</html>
'''


def get_scientific_template() -> str:
    """Get scientific HTML template with comprehensive analysis."""
    return '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>U-Probe Scientific Analysis Report - {protocol_name}</title>
    <style>
        body {{
            font-family: 'Times New Roman', serif;
            line-height: 1.8;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 30px;
            background-color: #fafafa;
        }}
        .container {{
            background-color: white;
            padding: 50px;
            border-radius: 5px;
            box-shadow: 0 2px 15px rgba(0,0,0,0.1);
        }}
        .header {{
            text-align: center;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 30px;
            margin-bottom: 40px;
        }}
        .header h1 {{
            color: #2c3e50;
            margin: 0;
            font-size: 2.8em;
            font-weight: normal;
        }}
        .header .subtitle {{
            color: #7f8c8d;
            font-size: 1.1em;
            margin-top: 15px;
            font-style: italic;
        }}
        .abstract {{
            background: #ecf0f1;
            padding: 25px;
            border-radius: 5px;
            margin: 30px 0;
            border-left: 5px solid #3498db;
        }}
        .abstract h3 {{
            color: #2c3e50;
            margin-top: 0;
        }}
        .section {{
            margin-bottom: 40px;
        }}
        .section h2 {{
            color: #2c3e50;
            border-bottom: 1px solid #bdc3c7;
            padding-bottom: 10px;
            font-size: 1.8em;
            font-weight: normal;
        }}
        .section h3 {{
            color: #34495e;
            font-size: 1.3em;
            margin-top: 25px;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .stat-card {{
            background: #f8f9fa;
            padding: 15px;
            border: 1px solid #dee2e6;
            text-align: center;
        }}
        .stat-value {{
            font-size: 1.6em;
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 4px;
        }}
        .stat-label {{
            color: #7f8c8d;
            font-size: 0.9em;
        }}
        .table-container {{
            overflow-x: auto;
            margin: 25px 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background: white;
            border: 1px solid #dee2e6;
        }}
        th, td {{
            padding: 8px 12px;
            text-align: left;
            border: 1px solid #dee2e6;
            font-size: 0.9em;
        }}
        th {{
            background-color: #2c3e50;
            color: white;
            font-weight: bold;
        }}
        .plot-container {{
            text-align: center;
            margin: 20px 0;
            page-break-inside: avoid;
            padding: 10px;
        }}
        .plot-container img {{
            max-width: 80%;
            max-height: 400px;
            height: auto;
            border: 1px solid #dee2e6;
        }}
        .plot-caption {{
            font-size: 0.9em;
            color: #7f8c8d;
            margin-top: 10px;
            font-style: italic;
        }}
        .method-section {{
            background: #f8f9fa;
            padding: 25px;
            border: 1px solid #dee2e6;
            margin: 25px 0;
        }}
        .method-section h3 {{
            color: #2c3e50;
            margin-top: 0;
        }}
        .citation {{
            font-size: 0.9em;
            color: #7f8c8d;
            font-style: italic;
        }}
        .footer {{
            text-align: center;
            margin-top: 50px;
            padding-top: 25px;
            border-top: 1px solid #dee2e6;
            color: #7f8c8d;
            font-size: 0.9em;
        }}
        .reference {{
            font-size: 0.9em;
            margin: 5px 0;
        }}
        .equation {{
            text-align: center;
            margin: 20px 0;
            padding: 15px;
            background: #f8f9fa;
            border: 1px solid #dee2e6;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>U-Probe Scientific Analysis Report</h1>
            <div class="subtitle">Comprehensive Probe Design and Quality Assessment</div>
            <div class="subtitle">Protocol: {protocol_name}</div>
            <div class="subtitle">Generated: {timestamp}</div>
        </div>
        
        {content}
        
        <div class="footer">
            <p><strong>U-Probe Analysis Pipeline</strong></p>
            <p>Scientific Report Template | Computational Biology Analysis</p>
            <p class="citation">For research use. Please cite appropriate references when publishing.</p>
        </div>
    </div>
</body>
</html>
'''


def generate_summary_content(summary_data: Dict[str, Any], plots: Dict[str, str]) -> str:
    """Generate summary content section."""
    content = []
    
    # Overall statistics
    content.append('<div class="section">')
    content.append('<h2>📊 Summary Statistics</h2>')
    
    # Basic info
    data_info = summary_data.get('data_info', {})
    total_probes = data_info.get('total_probes', 0)
    targets = data_info.get('targets', [])
    
    content.append('<div class="stats-grid">')
    content.append(f'''
        <div class="stat-card">
            <div class="stat-value">{total_probes:,}</div>
            <div class="stat-label">Total Probes</div>
        </div>
    ''')
    content.append(f'''
        <div class="stat-card">
            <div class="stat-value">{len(targets)}</div>
            <div class="stat-label">Target Regions</div>
        </div>
    ''')
    
    # Probe counts by target
    probe_counts = summary_data.get('probe_counts', {})
    if probe_counts:
        avg_probes = sum(probe_counts.values()) / len(probe_counts)
        content.append(f'''
            <div class="stat-card">
                <div class="stat-value">{avg_probes:.0f}</div>
                <div class="stat-label">Avg Probes/Target</div>
            </div>
        ''')
    
    content.append('</div>')
    
    # Probe count chart
    if 'probe_counts' in plots:
        content.append('<div class="plot-container">')
        content.append('<h4 style="color: #007acc; margin-bottom: 10px;">Probe Distribution by Target</h4>')
        content.append(f'<img src="data:image/png;base64,{plots["probe_counts"]}" alt="Probe Count Chart">')
        content.append('</div>')
    
    content.append('</div>')
    
    # Attribute statistics
    attribute_stats = summary_data.get('attribute_stats', {})
    if attribute_stats:
        content.append('<div class="section">')
        content.append('<h2>🔬 Attribute Analysis</h2>')
        
        for attr_name, stats in attribute_stats.items():
            content.append(f'<h3>{attr_name.replace("_", " ").title()}</h3>')
            
            # Statistics table
            content.append('<div class="table-container">')
            content.append('<table>')
            content.append('<tr><th>Statistic</th><th>Value</th></tr>')
            
            for stat_name, value in stats.items():
                if isinstance(value, float):
                    formatted_value = f'{value:.3f}'
                else:
                    formatted_value = str(value)
                content.append(f'<tr><td>{stat_name.title()}</td><td>{formatted_value}</td></tr>')
            
            content.append('</table>')
            content.append('</div>')
            
            # Add plots if available
            hist_key = f'{attr_name}_histogram'
            box_key = f'{attr_name}_boxplot'
            
            # Create a grid layout for plots if both histogram and boxplot exist
            has_hist = hist_key in plots
            has_box = box_key in plots
            
            if has_hist and has_box:
                content.append('<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 15px 0;">')
                content.append('<div class="plot-container" style="margin: 0;">')
                content.append(f'<h4 style="color: #007acc; margin-bottom: 10px;">{attr_name.replace("_", " ").title()} Distribution</h4>')
                content.append(f'<img src="data:image/png;base64,{plots[hist_key]}" alt="{attr_name} Histogram">')
                content.append('</div>')
                content.append('<div class="plot-container" style="margin: 0;">')
                content.append(f'<h4 style="color: #007acc; margin-bottom: 10px;">{attr_name.replace("_", " ").title()} by Target</h4>')
                content.append(f'<img src="data:image/png;base64,{plots[box_key]}" alt="{attr_name} Boxplot">')
                content.append('</div>')
                content.append('</div>')
            elif has_hist:
                content.append('<div class="plot-container">')
                content.append(f'<h4 style="color: #007acc; margin-bottom: 10px;">{attr_name.replace("_", " ").title()} Distribution</h4>')
                content.append(f'<img src="data:image/png;base64,{plots[hist_key]}" alt="{attr_name} Histogram">')
                content.append('</div>')
            elif has_box:
                content.append('<div class="plot-container">')
                content.append(f'<h4 style="color: #007acc; margin-bottom: 10px;">{attr_name.replace("_", " ").title()} by Target</h4>')
                content.append(f'<img src="data:image/png;base64,{plots[box_key]}" alt="{attr_name} Boxplot">')
                content.append('</div>')
        
        content.append('</div>')
    
    # Correlation plots
    scatter_plots = {k: v for k, v in plots.items() if '_scatter' in k}
    if scatter_plots:
        content.append('<div class="section">')
        content.append('<h2>📈 Correlation Analysis</h2>')
        
        # Create a grid layout for scatter plots if there are multiple
        scatter_items = list(scatter_plots.items())
        if len(scatter_items) > 1:
            # Use 2-column grid for multiple scatter plots
            content.append('<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 15px 0;">')
            for plot_name, plot_data in scatter_items:
                title = plot_name.replace('_scatter', '').replace('_vs_', ' vs ').title()
                content.append('<div class="plot-container" style="margin: 0;">')
                content.append(f'<h4 style="color: #007acc; margin-bottom: 10px;">{title}</h4>')
                content.append(f'<img src="data:image/png;base64,{plot_data}" alt="{title} Scatter Plot">')
                content.append('</div>')
            content.append('</div>')
        elif len(scatter_items) == 1:
            plot_name, plot_data = scatter_items[0]
            title = plot_name.replace('_scatter', '').replace('_vs_', ' vs ').title()
            content.append('<div class="plot-container">')
            content.append(f'<h4 style="color: #007acc; margin-bottom: 10px;">{title}</h4>')
            content.append(f'<img src="data:image/png;base64,{plot_data}" alt="{title} Scatter Plot">')
            content.append('</div>')
        
        content.append('</div>')
    
    return '\n'.join(content)


def generate_method_section(protocol: Dict[str, Any]) -> str:
    """Generate methods section for scientific template."""
    content = []
    
    content.append('<div class="method-section">')
    content.append('<h3>Methods</h3>')
    
    # Protocol information
    content.append('<h4>Probe Design Protocol</h4>')
    content.append(f'<p><strong>Protocol Name:</strong> {protocol.get("name", "N/A")}</p>')
    content.append(f'<p><strong>Description:</strong> {protocol.get("description", "N/A")}</p>')
    content.append(f'<p><strong>Genome:</strong> {protocol.get("genome", "N/A")}</p>')
    
    # Probe design parameters
    probes = protocol.get('probes', {})
    if probes:
        content.append('<h4>Probe Design Parameters</h4>')
        content.append('<ul>')
        for probe_name, probe_config in probes.items():
            content.append(f'<li><strong>{probe_name}:</strong> {probe_config.get("template", "N/A")}</li>')
        content.append('</ul>')
    
    # Quality filters
    filters = protocol.get('post_process', {}).get('filters', {})
    if filters:
        content.append('<h4>Quality Control Filters</h4>')
        content.append('<ul>')
        for filter_name, filter_config in filters.items():
            condition = filter_config.get('condition', 'N/A')
            content.append(f'<li><strong>{filter_name}:</strong> {condition}</li>')
        content.append('</ul>')
    
    content.append('</div>')
    
    return '\n'.join(content)


def save_html_report(
    df: pd.DataFrame,
    protocol: Dict[str, Any],
    output_path: Path,
    template_type: str = "detailed",
    plot_data: Optional[Dict[str, str]] = None
) -> Optional[Path]:
    """Save HTML report to file.
    
    Args:
        df: DataFrame containing probe data
        protocol: Protocol configuration
        output_path: Output file path
        template_type: Template type ('basic', 'detailed', 'scientific')
        plot_data: Dictionary of plot data (base64 encoded)
        
    Returns:
        Path to saved HTML file or None if failed
    """
    try:
        logger.info(f"Generating {template_type} HTML report...")
        
        # Get summary data
        summary_data = getattr(df, 'attrs', {}).get('summary_data', {})
        logger.info(f"Retrieved summary data from DataFrame attrs: {bool(summary_data)}")
        if not summary_data:
            # Try to load from temporary file (fallback)
            try:
                import tempfile
                import pickle
                import os
                
                temp_dir = tempfile.gettempdir()
                summary_file = os.path.join(temp_dir, 'uprobe_summary_data.pkl')
                if os.path.exists(summary_file):
                    with open(summary_file, 'rb') as f:
                        summary_data = pickle.load(f)
                    logger.info("Loaded summary data from temporary file")
            except Exception as e:
                logger.warning(f"Could not load summary data: {e}")
                summary_data = {}
        
        if not plot_data:
            plot_data = {}
        
        # Generate content
        content = generate_summary_content(summary_data, plot_data)
        
        # Add methods section for scientific template
        if template_type == "scientific":
            content += generate_method_section(protocol)
        
        # Get template
        if template_type == "basic":
            template = get_basic_template()
        elif template_type == "scientific":
            template = get_scientific_template()
        else:  # detailed
            template = get_detailed_template()
        
        # Fill template
        protocol_name = protocol.get('name', 'Unknown Protocol')
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        html_content = template.format(
            protocol_name=protocol_name,
            timestamp=timestamp,
            content=content
        )
        
        # Save to file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        logger.info(f"HTML report saved to: {output_path}")
        return output_path
        
    except Exception as e:
        logger.error(f"Error generating HTML report: {e}")
        return None
